DataKind-DC/capital-nature-ingest

ingest_scripts/GenericEventbriteIngester.py, ingest_scripts/fona_eventbrite.py
Scraper for the Friend of the National Arboretum, using their events on Eventbrite.
GenericEventbriteIngester is a reusable class that can be extended to other organizations on Eventbrite.
=> ENH: ingest FoNA events from Eventbrite

lambdas/arlington/Makefile, lambdas/arlington/lambda_function.py, lambdas/arlington/requirements.txt
Just a placeholder for Arlington County Parks and Recreation events. See Google Sheet reference [here](https://docs.google.com/spreadsheets/d/1znSHrheEjqmb6OhhZ0ADse844A0Qp9RhsApczMGWSKk/edit#gid=1708332455&range=B12).
=> ENH: Add Arlington County Parks and Recreation Events

lambdas/vnps/Makefile, lambdas/vnps/lambda_function.py, lambdas/vnps/requirements.txt
Lambda handler to pull events from [Virginia Native Plant Society](http://vnps.org/events) and dump into S3.
=> ENH: Add Virginia Native Plant Society Events

lambdas/fairfax/Makefile, lambdas/fairfax/lambda_function.py, lambdas/fairfax/requirements.txt
I started looking at Huntley Meadows Park events, as [listed](https://docs.google.com/spreadsheets/d/1znSHrheEjqmb6OhhZ0ADse844A0Qp9RhsApczMGWSKk/edit#gid=1708332455&range=B51) on our spreadsheet, and then noticed that it was possible to find all events for all Fairfax county parks [here](https://www.fairfaxcounty.gov/parks/park-events-calendar). I'm furloughed, so I did :stuck_out_tongue_winking_eye:
=> ENH: Add lambda handler for Fairfax county park events

lambdas/arlington/lambda_function.py
Replace events calendar web-scraper with the today-service API, which can be found in the network tab when you inspect this [page](https://today.arlingtonva.us/) after a page refresh. Using this API yields more nature-related events than the previous scraper, which just returned invasive plant removal events.
=> ENH: use today-service api to get all nature events (#24)

lambdas/nps/lambda_function.py
- removed the event category column
- added the time zone ("Eastern Standard Time")
- updated the event organizer to be the park name
- added the Event Cost Currency Symbol ("$")
=> FIX: update nps event schema in response to #30

tests/ans_test.py, tests/arlington_test.py, tests/casey_trees_test.py, tests/fairfax_test.py, tests/montgomery_test.py, tests/nps_test.py, tests/utils.py, tests/vnps_test.py
=> CLN: Test cleanup

.circleci/config.yml, lambdas/casey_trees/lambda_function.py, lambdas/nps/lambda_function.py, tests/fixtures/nps_test_fixtures.py, tests/nps_test.py
Also update the event organizer field in NPS module.
=> FIX: Fix csv writers

lambdas/vnps/lambda_function.py, tests/vnps_test.py
remove lambda handler and use main function
=> BLD: Refactor vnps to use main()

event_sources.md
@csmcallister I tried to make these changes earlier but not sure what happened to the request. Am I supposed to have edit privileges for this file? Last time I only clicked "propose changes" so this time I'm also trying the next thing that appeared, Create pull request. Sorry I'm not good with Github.
=> Added new sources and highlighted priority sources

get_events.py, requirements.txt
added solution works for ~50% of the 842 events in the last scrape. Bumping that up much higher will require more time though, as I'd need to re-examine how each of the individual scrapers works and then create a bespoke solution. Even then, getting to 100% coverage is a long shot.
=> ENH: prepend event descriptions with state (#77)

events/dug_network.py
Hi Scott, tried to filter events with non-empty start time. Please let me know if something needs to be changed. Thanks.
=> Filtering events with only start time

events/fona.py, tests/utils.py
Fixing the bool type test and a small typo in `fona.py`
=> TST: Fix bool test

README.md
Update README.md to include direct link to Eventbrite API
=> Update README.md to include direct link to Eventbrite API

events/eleventh_street.py, get_events.py, tests/eleventh_street_test.py
Added new event source: Eleventh Street Bridge Park, aka Building Bridges Across the River (BBAR)
=> ENH: Eleventh street #109

events/aws.py, events/dc_audubon.py, events/eleventh_street.py, get_events.py, tests/ans_test.py, tests/arlington_test.py, tests/casey_trees_test.py, tests/city_blossoms_test.py, tests/dc_audubon_test.py, tests/eleventh_street_test.py, tests/friends_test.py
- Added new scraper for DC Audubon Society using the Eventbrite API (used existing Eventbrite scrapers (e.g. FONA) as template)
=> ENH: New event source: DC Audubon Society (#126)

events/us_botanic_garden.py, get_events.py, tests/us_botanic_garden_test.py
Added new scraper for US Botanic Garden (makes requests to doubleknot to get event IDs up to 5 months out from current month, then uses BeautifulSoup to extract event information from event detail pages).
=> ENH: New event source: US Botanic Garden (#113)

events/ans.py
Scrape events for the current month & the next three months for ANS.
=> ENH: scrape events 3 months out :sparkles: (#176)

events/montgomery.py
This fix handles events like this [one](https://www.montgomeryparks.org/events/mudfest/)  where the event dates/times aren't formatted like the others. It also adds some logging to help debug this in the future.
=> FIX: handle unexpected event dates/times :bug: (#179)

events/nps.py, events/potomac_conservancy.py, get_events.py, tests/potomac_consercancy_test.py, utils/event_source_map.py
Adds a scraper for Potomac Conservancy. Also adds a check for API keys to the top of `get_events.py` to prevent redundant prompts for them.
=> ENH: scrape potomac conservancy :sparkles: (#171)

events/nps.py
Filters out some of the NPS parks since they are very far away.
=> FIX: filter out distant venues (#106)

events/eleventh_street.py
=> FIX: handle recurring events :bug:

events/casey_trees.py
Handle cases where there aren't any event categories.
=> FIX: handle case where categories are missing

events/mdflora.py, events/utils/event_source_map.py, get_events.py, tests/mdflora_test.py
Maryland Native Plant society from the calendar view.
=> ENH: MD native society scraper

events/montgomery.py, events/rcc.py
Out of the thousands of events we've scraped from this event source, we've now encountered one that denotes recurrence in the form of `"Wednesays, April 1 - ....."`. Although it is possible to figure that out, it's a lot of work for very little reward.
=> FIX: Ignore rare recurring weekday events

events/lfwa.py, events/nva_audubon_society.py
Little fixes. Using a context manager for request session in nva_audubon and correct logger in lfwa
=> FIX: random fixes

events/arlington.py, events/nova_parks.py
Replaces eventbrite with event source url for NOVA.
=> FIX: scrape NOVA website instead of eventbrite #242

events/city_blossoms.py, events/eleventh_street.py, events/loudoun_wildlife_conservancy.py, events/nova_parks.py, events/riverkeeper.py, events/us_botanic_garden.py
minor fixes and adding more logging
=> FIX: several fixes, add logging :loud_sound:

events/fairfax.py
=> FIX: handle fairfax paginated calendar #245

events/ans.py
=> FIX: include events with missing venue #246

events/utils/formatters.py, get_events.py
=> ENH: limit events to next 90 days #249

events/us_botanic_garden.py
=> FIX: dont log missing event categories #250

events/rcc.py, get_events.py, tox.ini
=> LOG: silence log for missing venues #247

events/city_blossoms.py
=> FIX: use collectionID in API #252 :bug:

events/dc_audubon.py, events/fona.py, events/friends_of_kenilworth_gardens.py, events/riverkeeper.py, events/sierra_club_md.py
closes #253 
also fixes all of the other eventrbite event sources to handle case of zero events on their page
=> Fix riverkeeper

events/city_blossoms.py, events/eleventh_street.py
=> FIX: hardcode venue #254 :bug:

README.md, events/tnc.py
=> FIX: Fix TNC

events/ans.py
=> FIX: handle bad JSON decoding :bug:
